class ChatMessage {
  final String id;
  final String senderId;
  final String senderName;
  final String text;
  final int timestamp;

  ChatMessage({
    required this.id,
    required this.senderId,
    required this.senderName,
    required this.text,
    required this.timestamp,
  });

  /// Creates a ChatMessage from a Firebase Realtime Database entry.
  /// [id] is the unique key generated by Firebase (.push()).
  /// [map] contains the values stored under that key.
  factory ChatMessage.fromMap(String id, Map<dynamic, dynamic> map) {
    return ChatMessage(
      id: id,
      senderId: map['senderId'] as String? ?? '',
      senderName: map['senderName'] as String? ?? 'Anonymous',
      text: map['text'] as String? ?? '',
      timestamp: map['timestamp'] as int? ?? 0,
    );
  }

  /// Converts the ChatMessage object into a Map for Firebase storage.
  /// Note: We usually let the database handle the [id] via the push() method.
  Map<String, dynamic> toMap() {
    return {
      'senderId': senderId,
      'senderName': senderName,
      'text': text,
      'timestamp': timestamp,
    };
  }

  /// Helper to check if a message is valid (not empty)
  bool get isValid => text.trim().isNotEmpty;
}